### ISSUE TITLE
Incorrect encoding of open and close double quotes and of ligatures

### ISSUE THREAD

**Issue by mark-summerfield** [yob/pdf-reader#211] opened 2017-03-22 09:11 UTC
The attached PDF contains a single line of text:

_This PDF contains ligatures, for example in “file” and “floor”._

(And of course the PDF really does have curly double quotes and fi and fl ligatures.)

However, this code:
```ruby
require 'pdf/reader'
filename = ARGV.pop
reader = PDF::Reader.new(filename)
reader.pages.each do |page|
  puts page.text
end
```
Produces this **incorrect** output:
_This PDF contains ligatures,for example in …‡le†and …ˆoor†._

[test.pdf](https://github.com/yob/pdf-reader/files/860872/test.pdf)

**Comment by yob** [comment] 2019-10-26 12:45
Huh. This is a super simple case (a built-in font with a difference table for non-standard characters) and I can confirm it's broken. In fact, it's been broken since #64 merged (gem versions >= 1.3.0).

I guess there's a gap in the spec suite...

**Closed** 2019-10-26 13:35 UTC
