### ISSUE TITLE
Pass into custom encoding differences

### ISSUE THREAD

**Issue by westonplatter** [yob/pdf-reader#215] opened 2017-04-13 04:14 UTC
Based on https://github.com/yob/pdf-reader/blob/master/spec/encoding_spec.rb, I know that you can set the encoding and make custom substitutions for non-UTF-8 encodings. I'm trying to parse a non standard "-" character in [this PDF](https://drive.google.com/file/d/0B5gTnuoDM9q9dklYTVlUQmpETlk/view?usp=sharing).

Is there a simple way to do this?

**Comment by yob** [comment] 2019-10-26 13:42
Thanks for taking the time to report an issue and apologies for not looking into it earlier.

It's currently not possible to customise the encoding behavior during text extraction.

Is there a specific problem with exporting hyphens from that document? Or is the extraction working, but you'd like hyphens extracted as something different?

Given the time since this was opened and that I don't have enough details to reproduce it, I'm going to close it. I'm happy to look into it further if you want to provide more details.

**Closed by yob** 2019-10-26 13:42 UTC
