### ISSUE TITLE
input must be an IO-like object or a filename

### ISSUE THREAD

**Issue by Faisal-nfl** [yob/pdf-reader#285] opened 2019-01-01 14:17 UTC
I tried [extract_images.rb](https://github.com/yob/pdf-reader/blob/master/examples/extract_images.rb)
When I try this 
filename = File.expand_path(File.dirname(__FILE__)) + "/public/abc.pdf"
extractor = ExtractImages::Extractor.new

it says "input must be an IO-like object or a filename"

**Comment by yob** [comment] 2019-01-01 23:33
Hi,

Can you include the code where you call `PDF::Reader.new` or `PDF::Reader.open`? That probably the line where the issue is.

**Comment by encoreshao** [comment] 2019-02-17 15:10
Hi, @Faisal-nfl ,

The same error occurred in my project. Finally, I found that I was using the wrong file path. I think maybe you should double check the file path in the code.

Encore

**Comment by yob** [comment] 2019-11-21 13:09
I'm going to close this issue, but if you have further information please feel free to re-open it.

**Closed by yob** 2019-11-21 13:09 UTC
