### ISSUE TITLE
lzw.rb / decode : can't convert nil into String

### ISSUE THREAD

**Issue by pinpudding** [yob/pdf-reader#90] opened 2013-03-07 08:18 UTC
When trying to extract text of document https://dl.dropbox.com/u/39311630/JFE-June%2B79.pdf  I get 
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/lzw.rb:91:in `decode'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/filter/lzw.rb:14:in`filter'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/stream.rb:63:in `block in unfiltered_data'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/stream.rb:62:in`each'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/stream.rb:62:in `each_with_index'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/stream.rb:62:in`unfiltered_data'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/page.rb:116:in `block in raw_content'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/page.rb:113:in`map'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/page.rb:113:in `raw_content'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/page.rb:105:in`walk'
vendor/bundle/ruby/1.9.1/bundler/gems/pdf-reader-65b417aea904/lib/pdf/reader/page.rb:75:in `text'

**Comment by yob** [comment] 2017-01-02 15:34
Shortly after this issue was reported, a fix for the lzw filter was merged in c5866dad. Unfortunately I can't download the PDF that was having issues any more, so I can't confirm if that fix would help in this case.

Given the passage of time, I'll close this for now but feel free to open it if the issue is still happening.

**Closed by yob** 2017-01-02 15:34 UTC
